### ISSUE TITLE
Not able to write file to ftp server. 

### ISSUE THREAD

**Issue by dileep-p** [sensu-plugins/sensu-plugins-ftp#2]
[root@sensu~]# /opt/sensu/embedded/bin/check-ftp.rb  -H localhost -u xxxx -p 'yyyyy' -w
false
CheckFTP CRITICAL: Connection error: 500 Illegal PORT command.

[root@sensu~]# /opt/sensu/embedded/bin/check-ftp.rb  -H localhost -u xxxx -p 'yyyyy' -w -x
true
CheckFTP CRITICAL: Connection timed out

**Comment by eheydrick** [comment]
Can you try with the latest release, 1.0.0.

**Comment by eheydrick** [comment]
Closing due to age. Feel free to reopen if this is still an issue.
