### ISSUE TITLE
Timeout.timeout

### ISSUE THREAD

**Issue by Blue0ctober** [sensu-plugins/sensu-plugins-ftp#5]
The following output is being seen when ran with the current embedded ruby:
> /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-plugins-ftp-1.1.0/bin/check-ftp.rb:89:in `run': Object#timeout is deprecated, use Timeout.timeout instead.

[Line 89](https://github.com/sensu-plugins/sensu-plugins-ftp/blob/ea746ee200f78085552ff7338ec0dc37f499529e/bin/check-ftp.rb#L89) should be changed from : `timeout(config[:timeout]) do`

to: `Timeout.timeout(config[:timeout]) do`

Expected output:

> CheckFTP OK

**Comment by eheydrick** [comment]
Ah yeah, that should get fixed up. Can you put together a PR for that. There was one (#4) but it was closed due to inactivity.
